<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
		<string>ini</string>
		<string>conf</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>Config — INI</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.configobj</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[\s|=|0-9]*(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.configobj</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.configobj</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.configobj</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\[.+\]</string>
			<key>name</key>
			<string>entity.name.component.configobj</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([^=]+)=\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.configobj</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_quoted_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_quoted_single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#normal_value</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^[^=]+$</string>
			<key>name</key>
			<string>invalid.illegal.configobj</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>normal_value</key>
		<dict>
			<key>begin</key>
			<string></string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>constant.character.configobj</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.configobj</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(;).*</string>
					<key>name</key>
					<string>comment.line.number-sign.configobj</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted_double</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(""")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.configobj</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>double quoted string</string>
					<key>end</key>
					<string>((?&lt;=""")(")""|""")</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.configobj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.empty-string.double.configobj</string>
						</dict>
					</dict>
					<key>name</key>
					<string>constant.character.configobj</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted_single</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(''')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.configobj</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>single quoted string</string>
					<key>end</key>
					<string>((?&lt;=''')(')''|''')</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.configobj</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.empty-string.single.configobj</string>
						</dict>
					</dict>
					<key>name</key>
					<string>constant.character.configobj</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.configobj</string>
	<key>uuid</key>
	<string>ED8885D6-BA93-476A-B1AB-FC3C48C5CFBE</string>
</dict>
</plist>
